// orchestrator/setup.js — interactive, one-value-at-a-time .env setup.
//
// Built to replace the raw-file-editing approach this session, which went badly:
// multiple stray Notepad windows, values landing in the wrong field, secrets pasted
// where they shouldn't be. This asks ONE question at a time in the terminal, with
// nothing else on screen to misplace things into, and writes the file itself.
//
// Run: npm run setup

import { createInterface } from 'node:readline/promises';
import { writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const ENV_PATH = new URL('./.env', import.meta.url);

const FIELDS = [
  {
    key: 'SUPABASE_URL',
    prompt: 'Supabase project URL (looks like https://xxxxxxxx.supabase.co): ',
    secret: false
  },
  {
    key: 'SUPABASE_SERVICE_ROLE_KEY',
    prompt: 'Supabase SECRET key (Settings -> API Keys -> secret, NOT publishable): ',
    secret: true
  },
  {
    key: 'ANTHROPIC_API_KEY',
    prompt: 'Anthropic API key (console.anthropic.com -> API Keys), or press Enter to skip: ',
    secret: true,
    optional: true
  },
  {
    key: 'PUBLISH_EXTERNAL_URL',
    prompt: 'Deployed publish-external function URL, or press Enter to skip: ',
    secret: false,
    optional: true
  }
];

async function main() {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log('Hotel NEXUS orchestrator setup — one value at a time, nothing else on screen.');
  console.log(`This writes directly to: ${ENV_PATH.pathname}\n`);

  const values = {};
  for (const field of FIELDS) {
    const answer = (await rl.question(field.prompt)).trim();
    if (!answer && !field.optional) {
      console.log('This one is required — try again.');
      const retry = (await rl.question(field.prompt)).trim();
      values[field.key] = retry;
    } else {
      values[field.key] = answer;
    }
    // Never echo back a secret value, even to confirm it was received.
    console.log(field.secret ? '  -> saved (hidden)\n' : `  -> saved: ${values[field.key] || '(skipped)'}\n`);
  }

  rl.close();

  const content = [
    '# Hotel NEXUS orchestrator — generated by npm run setup',
    `SUPABASE_URL=${values.SUPABASE_URL}`,
    `SUPABASE_SERVICE_ROLE_KEY=${values.SUPABASE_SERVICE_ROLE_KEY}`,
    `ANTHROPIC_API_KEY=${values.ANTHROPIC_API_KEY || ''}`,
    `PUBLISH_EXTERNAL_URL=${values.PUBLISH_EXTERNAL_URL || ''}`,
    'NIGHT_SHIFT_CRON=0 2 * * *',
    ''
  ].join('\n');

  await writeFile(ENV_PATH, content, 'utf8');
  console.log('Done. Saved to .env — nothing else needs editing by hand.');
}

main().catch((err) => {
  console.error('Setup failed:', err.message);
  process.exit(1);
});
